### ISSUE TITLE
Training cost details

### ISSUE THREAD

**Issue by realmoment2017** [TencentARC/SmartEdit#16]
Hello, I wonder how long does it take to train each stage for the 7B model? I tested the stage 1 training on 8xA100 and it took like 60 hours with the default config file. I wonder if this aligns with you observations? Thank you.

**Comment by yuzhou914** [comment]
Thanks for your interest. All training processes are done by 8 GPUs, SmartEdit-7B by 8xA100, SmartEdit-13B by 8xH800. Since there are two stages for training, the total training process may last around 3 days.

**Comment by realmoment2017** [comment]
To follow up, what is the training time for the each stage? Could you please give a bit more information? As I mentioned, it seems like only the first stage would take 3 days.

**Comment by yuzhou914** [comment]
It might be hard for me to remember the very accurate training time since we have finished this half of a year ago, I could only give out the rough total time since H800 will be much faster (maybe A100 will be longer), while if your inference for the stage-1 training is correct by the given scripts, then the training process must be normal.
