### ISSUE TITLE
How about  finetuen custom reasoningEditing dataset?

### ISSUE THREAD

**Issue by wy3406** [TencentARC/SmartEdit#19]
Hi，Thank you very much for your work. 
I want to finetune my  reasoningediting data on your ckpt weight. Do you have any suggestions

**Comment by yuzhou914** [comment]
Thank you for your interests to our work. If you want to finetune your instruction-based editing dataset, I suggest that you can 1. prepare your data with spatial consistency in input-output-instruction triplet. 2. since you may use the pre-trained editing weight, you can use joint training strategy, which mixes existing editing datasets (such as datasets used in SmartEdit) and your dataset in a reasonable ratio. 3. update your evaluation set if you want to stimulate new ability that the previous editing model cannot do.
