### ISSUE TITLE
[Doubt]-Output Image size

### ISSUE THREAD

**Issue by alphacoder01** [TencentARC/SmartEdit#32]
What resolution gives best results? I tested with 256, 384 and 512.
256x256 seems to be giving the best results. Wanted to know if that's the case

**Comment by yuzhou914** [comment]
Thanks for your interest in our work. Since all the training processes are trained on 256x256, and 256x256 might be the best results when inference, 384x384 are also well, while 512x512 might not be very good when we conduct some examples. I think delving into the resolution problem is also a meaningful point for future research.

**Comment by alphacoder01** [comment]
Thanks for your reply!!
